"use strict";
exports.__esModule = true;
exports.TweetRepository = exports.UserRepository = void 0;
var client_1 = require("./client");
var schema_1 = require("./schema");
var TweetRepository = client_1.RedisClient.fetchRepository(schema_1.tweetSchema);
exports.TweetRepository = TweetRepository;
TweetRepository.createIndex();
var UserRepository = client_1.RedisClient.fetchRepository(schema_1.userSchema);
exports.UserRepository = UserRepository;
UserRepository.createIndex();
