"use strict";
exports.__esModule = true;
exports.linkedin = exports.twitter = exports.coffee = exports.send = exports.barChart = exports.edit = exports.clock = exports.follower = exports.reply = exports.retweet = exports.heart = exports.IconWrapper = void 0;
var feather_icons_1 = require("feather-icons");
var IconWrapper = function (_a) {
    var svg = _a.svg, className = _a.className, style = _a.style;
    return <div className={className} style={style} dangerouslySetInnerHTML={{ __html: svg }}/>;
};
exports.IconWrapper = IconWrapper;
exports.heart = <exports.IconWrapper svg={feather_icons_1["default"].icons.heart.toSvg()} className="icon icon-heart"/>;
exports.retweet = <exports.IconWrapper svg={feather_icons_1["default"].icons.repeat.toSvg()} className="icon icon-retweet"/>;
exports.reply = <exports.IconWrapper svg={feather_icons_1["default"].icons['message-square'].toSvg()} className="icon icon-reply"/>;
exports.follower = <exports.IconWrapper svg={feather_icons_1["default"].icons.user.toSvg()} className="icon icon-user"/>;
exports.clock = <exports.IconWrapper svg={feather_icons_1["default"].icons.clock.toSvg()} className="icon icon-clock"/>;
exports.edit = <exports.IconWrapper svg={feather_icons_1["default"].icons.edit.toSvg()} className="icon icon-edit"/>;
exports.barChart = <exports.IconWrapper svg={feather_icons_1["default"].icons['bar-chart-2'].toSvg()} className="icon icon-bar-chart"/>;
exports.send = <exports.IconWrapper svg={feather_icons_1["default"].icons.send.toSvg()} className="icon icon-send"/>;
exports.coffee = <exports.IconWrapper svg={feather_icons_1["default"].icons.coffee.toSvg()} className="icon icon-coffee"/>;
exports.twitter = <exports.IconWrapper svg={feather_icons_1["default"].icons.twitter.toSvg()} className="icon icon-twitter"/>;
exports.linkedin = <exports.IconWrapper svg={feather_icons_1["default"].icons.linkedin.toSvg()} className="icon icon-linkedin"/>;
