import { NextPage } from 'next'
import Head from 'next/head'
import {Button, Col, Row} from 'react-bootstrap';

import styles from '../styles/Home.module.css'
import {CurrentStats, TwitterApiResponseData} from '../lib/types';
import Banner from '../components/stats/Banner';
import Title from '../components/common/Title';
import Tweet from '../components/entities/Tweet';
import Layout from '../components/common/Layout';
import {getRecentTweets} from '../lib/repos/tweets';
import {calcBatchTweetStats, calcBatchUserStats} from '../lib/utils/stats';
import {getTweetUrl} from '../lib/utils/tweets';
import {aboutStats} from '../lib/constants';
import Creator from '../components/entities/Creator';


const Home: NextPage<TwitterApiResponseData & {stats: CurrentStats}> = ({tweets, stats}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Layout className="layout animation about">
            <Row className="gx-0">
                <Col lg={6} className="col-stats">
                    <Banner className="mt-5 mt-lg-0" title={<Title prefix="App" className="top-50 text-center">Stats</Title>} stats={aboutStats} />
                </Col>

                <Col lg={6} className="px-1 px-lg-3 mt-5 mt-lg-0">
                    <Title prefix="About" className="mt-4 animated-text text-center text-lg-start">Next.Js Crowd</Title>
                    <p className="animated-text mb-3 text-center text-lg-start">
                        This app was created exclusively for the {' '}
                        <a href="https://dev.to/devteam/announcing-the-redis-hackathon-on-dev-3248" target="_blank">#RedisHackathon</a> on {' '}
                        <a href="https://dev.to" target="_blank">Dev.to</a>. We used the following stack: Redis, Next.Js, React.Js, HTML, CSS3, TypeScript, JavaScript, Node.Js and Google Cloud Run.

                        <br /><br />Its creators are: </p>
                    
                    <Creator
                        onClick={() => {
                            window.open('https://www.linkedin.com/in/maureen-ononiwu/', '_blank')
                        }}
                        data={{name: 'Maureen Ononiwu', title: 'Back-end Developer', profile_image_url: '/images/maureen100x100.jpg', description: `Back-end and DevOps engineer with approximately 2 years of experience learning and mastering technologies, working independently as well as with teams building software solutions.`}}
                    />

                    <Creator
                        onClick={() => {
                            window.open('https://buhalbu.com/hire', '_blank')
                        }}
                        data={{name: 'Sashe Vuchkov', title: 'Full-stack Developer', profile_image_url: '/images/sashe100x100.jpg', description: `Bulgarian Blogger. Technical SEO Guy. JS & Next.Js Developer. React.Js Ninja, Rapid Learner. Creator of BuhalBu's Kit - It's All About Fast & Sleek Next.Js Apps`}}
                    />
          
                </Col>
            </Row>
        </Layout>
    </>
  )
}

export default Home


export const getServerSideProps = async () => {
    const data = await getRecentTweets();

    const tweetStats = calcBatchTweetStats(data.tweets);
    const currentStats: CurrentStats = {
        tweets: tweetStats,
        users: calcBatchUserStats(data.users, tweetStats),
    }

    return {props: {...data, stats: currentStats}};
}