import { NextPage } from 'next'
import Head from 'next/head'
import {Button, CloseButton, Col, Modal, Row} from 'react-bootstrap';
import {CurrentStats, FormattedUser} from '../lib/types';
import Banner from '../components/stats/Banner';
import Title from '../components/common/Title';
import User from '../components/entities/User';
import Layout from '../components/common/Layout';
import {useState} from 'react';
import UserDetails from '../components/modals/UserDetails';

const Home: NextPage<{ users: FormattedUser[] } & {stats: CurrentStats}> = ({users, stats}) => {
    const [selectedUser, setSelectedUser] = useState<FormattedUser|null>(null);
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout className="layout index animation">
            {selectedUser && <UserDetails user={selectedUser} onClose={() => {
                setSelectedUser(null);
            }} />}
            <Row className="gx-0">
                <Col lg={6} className="col-stats">
                    <Banner className="mt-5 mt-lg-0" title={<Title prefix="Users" className="top-50 text-center">Stats</Title>} stats={stats.users} />
                </Col>

                <Col lg={6} className="px-3 mt-5 mt-lg-0">
                    <Title prefix="Top 3" className="mt-4 animated-text text-center text-lg-start">Users</Title>
                    <p className="animated-text mb-3 text-center text-lg-start">Our algorithm ranked these three users as the most prominent ones now who mentioned the React.Js framework Next.js.</p>
                    {users && users.slice(0, 3).map(user => <User key={user.id} data={user} onClick={() => setSelectedUser(user)} />)}
                </Col>
            </Row>
            <Row className="gx-0">
                <Col lg={6} className="px-1 px-lg-3 mt-5 mb-4 offset-lg-3 text-center">
                    <Title prefix="All" className="mt-2 animated-text">Users</Title>
                    <p className="animated-text">Here is a list of all users who talked about Next.Js today</p>
                </Col>
            </Row>
            <Row className="gx-0">
                {users && users.slice(0, 10).map(user =>
                    <Col key={user.id} lg={6} className="px-1 px-lg-3">
                        <User data={user} onClick={() => {
                            setSelectedUser(user)
                        }} />
                    </Col>
                )}
            </Row>
            <Row className="gx-0">
                <Col lg={6} className="offset-lg-3 px-1 px-lg-3 animated-text">
                    <Button variant="outline-light" className="w-100 load-more" >Load More</Button>
                </Col>
            </Row>
        </Layout>
    </>
  )
}

export default Home


export const getServerSideProps = async () => {

    const stats: CurrentStats = {
        tweets: {
          total_tweets: 100,
          total_likes: 100,
          total_replies: 100,
          total_retweets: 100,
        },
        users: {
            total_users: 100,
            total_engagement: 100,
            total_engagement_rate: '10%',
            total_followers: 100,
        }
    }

    return {props: {tweets: [], users: [], stats: stats}};
}